import os
ROOT = os.path.join(os.path.dirname(__file__))
CSS_STYLE = os.path.join(ROOT, "css/style.css")
CSS_DIR = os.path.join(ROOT, "css")
UI_DIR = os.path.join(ROOT, "gui/ui")
CONFIG = os.path.join(ROOT, "etc/config.json")
STAT_CONFIG = os.path.join(ROOT, "etc/stat.json")
APPEARANCE = os.path.join(ROOT, "etc/app.json")
ICON = os.path.join(ROOT, "resource/icons")
ETC = os.path.join(ROOT, "etc")
SOUND = os.path.join(ROOT, "resource/sound")